FROM atlassian/bamboo-agent-base
USER root

COPY jdk-8u101-linux-x64.tar.gz /var/lib/jdk-8u101-linux-x64.tar.gz
RUN cd /var/lib && tar zxfv jdk-8u101-linux-x64.tar.gz && ln -s /var/lib/jdk-8u101-linux-x64/bin/java /usr/local/bin/java
RUN apt update && apt install -y openssl libapr1-dev autoconf maven git gnupg
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && apt update && apt install -y docker-ce
RUN ln -sf /usr/share/maven /opt/maven

USER ${BAMBOO_USER}
RUN ${BAMBOO_USER_HOME}/bamboo-update-capability.sh "system.builder.mvn3.Maven 3.3" /usr/share/maven
RUN ${BAMBOO_USER_HOME}/bamboo-update-capability.sh "system.git.executable" /usr/bin/git